org: navy
space: integration
space-developer:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - lieutenant
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups:
  - sailors
allow-ssh: false
enable-space-quota: false
enable-security-group: false
enable-remove-users: true
isolation_segment: ""
named-security-groups: []
named_quota: ""
