---
name: concourse

releases:
- name: openldap
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: ldap
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: n1-standard-1
  vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # this instance group to your ELB
  - lb
  stemcell: trusty
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: openldap
    release: openldap
    properties:
      ldap:
        ssl:
          active: true
          server_cert: (( file $ldap_cert_file ))
          server_key: (( file $ldap_key_file ))
          ca_cert: (( file $ldap_cert_file ))
          olcRootPW: (( grab $ldap_db_password ))
          olcSuffix: (( grab $ldap_admin_user ))
          olcRootDN: (( grab $ldap_config_dn ))

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
