enabled: true
ldapHost: "172.17.0.2"
ldapPort: 389
use_tls: false
bindDN: "cn=admin,dc=example,dc=org"
userSearchBase: "ou=people,o=sevenSeas,dc=example,dc=org"
userNameAttribute: "uid"
userMailAttribute: "mail"
userObjectClass: "inetOrgPerson"
groupSearchBase: "ou=groups,o=sevenSeas,dc=example,dc=org"
groupAttribute: "uniqueMember"
origin: ldap
insecure_skip_verify: ""
ca_cert: ""
